name: Artillery Action to test endpoint function users-userId-tasks

on:
  push:
    # Action is called when a branch is merged with development
    branches:
      - development  

# Set up env variables for Node and Python
# Note: there is no Python functionality yet, but there will be eventually for uploadiing results to S3
env:
  NODE_VERSION: '14'  # the version of node we are using
  NPM_CONFIG_PREFIX: "~/.npm-global" # Required to set path for artillery call
  PYTHON_VERSION: '3.8' # the version of python we are using

jobs:
  artillery-test-users-user_id-tasks:
    # Create ubuntu VM for actions
    runs-on: ubuntu-latest 

    steps:
    #Checkout current repo
    - name: 'Checkout Repository GitHub Action' 
      uses: actions/checkout@v2

    #Setup Node
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        check-latest: true
    
    #Setup node package manager
    - name: 'Run npm init'
      run: npm init -y

    #install artillery
    - name: Run npm install artillery  
      run: npm install -g artillery

    #Get current date for outputted file name
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    # Call artillery test located at ./test/artillery/artillery-users-user_id-tasks.yaml
    # Return results to json
    - name: Run Artillery Test
      run: /home/runner/.npm-global/lib/node_modules/artillery/bin/artillery run --output artillery-test-users-user_id-tasks_${{ steps.date.outputs.date }}.json ./test/artillery/artillery-perf-test-users-user_id-tasks.yaml

    # Use preexisting action to upload to S3
    # This will be changed to my own python script
    # https://github.com/zdurham/s3-upload-github-action
    - name: Upload file to S3 using zdurham s3-upload-github-action
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
        FILE: artillery-test-users-user_id-tasks_${{ steps.date.outputs.date }}.json
        AWS_REGION: 'us-west-2'
        S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME_ARTILLERY }} 
        S3_KEY: artillery-test-users-user_id-tasks_${{ steps.date.outputs.date }}.json
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}