name: sls art performance test
  on:
    push:
      -development 

jobs:
  slsart-perf:
    name: artillery performance test
    runs-on: ubuntu-latest 

  env:
    NPM_CONFIG_PREFIX: "~/.npm-global"
    STAGE_NAME: users-perf-test

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with: 
        node-version: '14'
        #according to node js website, version 15 was just released, not sure if this can be used too
        check-latest: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: installing serverless-artillery
      run: |
        npm install -g serverless-artillery
    - name: deploying invoking and removing functions
      run: |
        ~/.npm-global/bin/slsart deploy --stage $STAGE_NAME
        ~/.npm-global/bin/slsart invoke -s ../test/artillery/performance-test-user.yml --stage $STAGE_NAME
        ~/.npm-global/bin/slsart remove --stage $STAGE_NAME
    #I wasn't sure if I was supposed to leave the results.json blank or not, it looks like there was nothing in it


