name: sql injection test for users/userid/tasks post

on:
  push:
    branches:
      - development
env:
  NODE_VERSION: '10.x'
  TEST_CASE_BODY: "{\"title\": \"injection\", \"description\": \"'hacked'); DELETE FROM users WHERE userId > 1020; -- \"}"
  RESULT_FILE_PATH: ../../test/results/sql-injection-users-userid-tasks-post.json

jobs:
  POST-test-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%F_%H-%M-%S')"
      - name: curl
        run: |
          curl -v -X POST -d '{"title": "injection", "description": "'hacked'); DELETE FROM users WHERE userId > 1020; -- "}' https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1078/tasks?


